### ISSUE TITLE
Rewrite STRIPS background section

### ISSUE THREAD

**Issue by kris701** [kris701/MARMA#226]
Remember related works in background
# Strips/planning task:
* Grounded STRIPS
  * What is a state?
  * Grounded atom (or fact)
  * Example
* Lifted STRIPS
  * (lifted) atom (or fact)
  * Example

**Comment by jamadaha** [comment]
Missing examples, as I have no idea how to express a whole PDDL domain + problem in succulent manner.

**Comment by kris701** [comment]
Putting examples into a seperate PDDL section seems to be a reasonable fix for this.
